# Generated by Django 3.0.3 on 2020-05-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200520_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dtype',
            field=models.CharField(choices=[('PP', 'Passport'), ('ID', 'Identity card'), ('OT', 'Others')], max_length=2),
        ),
    ]
