# Generated by Django 3.0.3 on 2020-05-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200520_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dtype',
            field=models.CharField(choices=[('ID', 'Identity card'), ('OT', 'Others'), ('PP', 'Passport')], max_length=2),
        ),
    ]
