# Generated by Django 3.0.3 on 2020-05-21 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customer_data_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data_sheet',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.DataSheet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='dtype',
            field=models.CharField(choices=[('OT', 'Others'), ('PP', 'Passport'), ('ID', 'Identity card')], max_length=2),
        ),
    ]
