# Generated by Django 3.0.3 on 2020-05-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200520_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.ManyToManyField(to='app.Profession'),
        ),
        migrations.AlterField(
            model_name='document',
            name='dtype',
            field=models.CharField(choices=[('ID', 'Identity card'), ('PP', 'Passport'), ('OT', 'Others')], max_length=2),
        ),
    ]
